name: publish_version
on:
  push:
    tags:    
      - 'v*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker build . --tag ghcr.io/badgerloop-software/chase-car-dashboard-image:${{ github.ref_name }}
          docker push ghcr.io/badgerloop-software/chase-car-dashboard-image:${{ github.ref_name }}
