name: publish
on: [push]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        uses: docker/login-action@v1
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        run: |
          docker build . --tag ghcr.io/badgerloop-software/chase-car-dashboard-image:latest
          docker push ghcr.io/badgerloop-software/chase-car-dashboard-image
