name: publish
on: [push]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github_actor }}
          password: ${{ secrets_GITHUB_TOKEN }}
      - run: |
          docker build . --tag ghcr.io/badgerloop-software/chase-car-dashboard-image:latest
          docker push ghcr.io/badgerloop-software/chase-car-dashboard-image
